"""empty message

Revision ID: 194685814da8
Revises: d3b19fed092e
Create Date: 2018-10-31 20:41:31.679135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194685814da8'
down_revision = 'd3b19fed092e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'modified_at')
    op.drop_column('todo', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('todo', sa.Column('modified_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
